//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPTC.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarifs
    {
        public int id_tarifs { get; set; }
        public string tarifs_name { get; set; }
        public int tarifs_category { get; set; }
        public double tarifs_price { get; set; }
        public string tarifs_description { get; set; }
        public string tarifs_photo { get; set; }
        public int tarifs_provider { get; set; }
        public int tarifs_count { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Providers Providers { get; set; }
    }
}
